### PR TITLE
208 update difficulty to hard

### LINKED ISSUE #208: Update Difficulty to Hard
If the difficulty is normal in Minecraft, then there's a 75% chance that you can't convert a zombie villager.

### PR DESCRIPTION
**Pull request by lucas2kdk**

### CODE REVIEW

**Comment by Fuglen** [comment]
Wait, I'm pretty sure that Vanilla is on normal but it might not be in Git if it was changed in the game. Why do we want the difficulty on hard, where is the issue on this? 😅

**Comment by Fuglen** [comment]
Found the issue nvm

**Comment by lucas2kdk** [comment]
@Fuglen Since you found the issue, can you approve the review ?

**Comment by Fuglen** [comment]
> @Fuglen Since you found the issue, can you approve the review ?

Not yet, as this would change the difficulty for our survival servers and I don't see why there is an issue with the zombie villagers? 

Easy difficulty is way too easy for most players and they get bored. Hard is way too hard for most players. I see normal as the only choice as a balanced difficulty for everyone.

**Comment by lucas2kdk** [comment]
Currently, zombies only have a 100% chance of turning villagers to zombie villagers after killing them when playing in Hard mode. But in easy mode, you have a 100% of your villager being lost forever when it is killed by a zombie. (Normal mode is 50% chance). Losing a villager is far worse than having one (temporarily) being changed to a zombie villager. The chances of converting to a zombie should be reversed for the difficulty modes (or even better should be 100% conversion to zombie villagers for all difficulty levels).

**Pull request closed without merging**
